#!/usr/bin/env bash
# Train the custom "Nabaztag" wake-word model (openWakeWord synthetic pipeline).
#
#   brain/scripts/train-wake-word.sh setup      # pinned training venv + checkouts
#   brain/scripts/train-wake-word.sh datasets   # background noise + RIR corpora
#   brain/scripts/train-wake-word.sh config     # write the training config
#   brain/scripts/train-wake-word.sh train      # generate clips + augment + train
#   brain/scripts/train-wake-word.sh validate   # load the ONNX, score real audio
#   brain/scripts/train-wake-word.sh provenance # (re)write the provenance record
#
# WHY A SCRIPT AND NOT THE NOTEBOOK: the upstream path is a Colab notebook. A
# notebook is not reproducible on the Bolt and leaves no record of WHAT produced
# the weights. Everything here is pinned and every stage is re-runnable.
#
# !! FLAGS NOT YET HARDWARE-VERIFIED !!  The stage flags below follow
# openWakeWord's documented train.py entry point, but this script has NEVER been
# executed end-to-end (it needs Linux + the multi-GB corpora). Treat the first
# run as a probe: if a flag differs in the pinned checkout, fix it HERE and
# report back, exactly as we did for Piper's --download-dir. Do not paper over a
# mismatch by hand-running steps — the point is that the recipe stays in git.
#
# BOUNDARY / LICENCES: openWakeWord is Apache-2.0 (dscripka/openWakeWord) and the
# sample generator is a BUILD-TIME tool — neither is imported by the brain, and
# nothing is vendored into this tree. The trained .onnx is OUR artifact; its
# provenance (phrase, versions, corpora, date) is recorded next to it. Confirm
# each corpus's licence before redistributing any model trained on it: we ship
# the RECIPE in git and keep the weights out (models/wake/ is gitignored).
#
# The runtime only ever loads the resulting models/wake/nabaztag.onnx.

set -euo pipefail
cd "$(dirname "$0")/../.."

REPO_DIR="$(pwd)"
WAKE_DIR="${WAKE_DIR:-$REPO_DIR/models/wake}"
TRAIN_DIR="${TRAIN_DIR:-$WAKE_DIR/.training}"
VENV="$TRAIN_DIR/venv"
PY="$VENV/bin/python"

# PINNED. Bump deliberately, never silently — a different commit is a different
# model, and the provenance record must say which one made the weights.
OWW_REPO="https://github.com/dscripka/openWakeWord"
OWW_REF="${OWW_REF:-v0.6.0}"
SAMPLE_GEN_REPO="https://github.com/rhasspy/piper-sample-generator"
SAMPLE_GEN_REF="${SAMPLE_GEN_REF:-master}"   # pin to a commit sha once verified

MODEL_NAME="${MODEL_NAME:-nabaztag}"
# The rabbit is bilingual, and Italian and English speakers say the name
# differently. Train on BOTH so an English "Nabaztag" is not a miss.
WAKE_PHRASES=("nabaztag" "na bazz tag" "nabaztagh")

log() { printf '\n== %s\n' "$*"; }

cmd_setup() {
  log "training venv (separate from the brain — build-time tooling): $VENV"
  mkdir -p "$TRAIN_DIR"
  python3 -m venv "$VENV"
  "$PY" -m pip install --upgrade pip >/dev/null

  if [ ! -d "$TRAIN_DIR/openWakeWord" ]; then
    git clone --depth 1 --branch "$OWW_REF" "$OWW_REPO" "$TRAIN_DIR/openWakeWord"
  fi
  if [ ! -d "$TRAIN_DIR/piper-sample-generator" ]; then
    git clone --depth 1 --branch "$SAMPLE_GEN_REF" "$SAMPLE_GEN_REPO" \
      "$TRAIN_DIR/piper-sample-generator"
  fi
  "$PY" -m pip install -e "$TRAIN_DIR/openWakeWord[training]"
  "$PY" -m pip install -r "$TRAIN_DIR/piper-sample-generator/requirements.txt"
  log "setup done. Next: datasets"
}

cmd_datasets() {
  # Negative/background audio and room impulse responses are what stop the model
  # firing at the TV. Sizes are multi-GB; this stage is the slow one.
  log "fetching background + RIR corpora into $TRAIN_DIR/data"
  mkdir -p "$TRAIN_DIR/data"
  "$PY" "$TRAIN_DIR/openWakeWord/openwakeword/data.py" --output_dir "$TRAIN_DIR/data" \
    || cat <<'EOF'

The bundled fetcher did not run. Download manually into $TRAIN_DIR/data:
  - a background-noise corpus (AudioSet subset / FMA),
  - the MIT room-impulse-response set,
  - openWakeWord's precomputed negative features.
Record what you used in the provenance file; licences differ per corpus.
EOF
}

cmd_config() {
  local cfg="$TRAIN_DIR/$MODEL_NAME.yaml"
  log "writing $cfg"
  {
    echo "# Generated by brain/scripts/train-wake-word.sh — edit there, not here."
    echo "model_name: $MODEL_NAME"
    echo "target_phrase:"
    for phrase in "${WAKE_PHRASES[@]}"; do echo "  - \"$phrase\""; done
    cat <<EOF
# Clip counts: the defaults in the upstream notebook. Raise n_samples if the
# validation stage shows misses on the real microphone.
n_samples: 30000
n_samples_val: 2000
output_dir: $TRAIN_DIR/$MODEL_NAME
piper_sample_generator_path: $TRAIN_DIR/piper-sample-generator
background_paths:
  - $TRAIN_DIR/data
rir_paths:
  - $TRAIN_DIR/data/mit_rirs
# Bilingual: the rabbit answers to it and en speakers alike.
tts_language: [it, en]
EOF
  } > "$cfg"
  echo "config written; review it before training"
}

cmd_train() {
  local cfg="$TRAIN_DIR/$MODEL_NAME.yaml"
  [ -f "$cfg" ] || { echo "no config — run 'config' first" >&2; exit 1; }
  log "training $MODEL_NAME (long: synthetic clips, augmentation, then the model)"
  "$PY" "$TRAIN_DIR/openWakeWord/openwakeword/train.py" \
    --training_config "$cfg" --generate_clips --augment_clips --train_model
  local produced="$TRAIN_DIR/$MODEL_NAME/$MODEL_NAME.onnx"
  [ -f "$produced" ] || { echo "training produced no $produced" >&2; exit 1; }
  mkdir -p "$WAKE_DIR"
  cp "$produced" "$WAKE_DIR/$MODEL_NAME.onnx"
  cmd_provenance
  log "model at $WAKE_DIR/$MODEL_NAME.onnx"
  echo "Point config.yaml at it:  wake:\n    models: [models/wake/$MODEL_NAME.onnx]"
}

cmd_validate() {
  # A model that trains cleanly can still be useless on the real microphone.
  # Score it on whatever WAVs you drop in, then confirm on the rabbit itself.
  local model="$WAKE_DIR/$MODEL_NAME.onnx"
  [ -f "$model" ] || { echo "no model at $model — train first" >&2; exit 1; }
  local clips="${1:-$TRAIN_DIR/validation-clips}"
  mkdir -p "$clips"
  log "scoring $model against WAVs in $clips (16 kHz mono)"
  "$PY" - "$model" "$clips" <<'EOF'
import sys, wave, numpy as np
from openwakeword.model import Model

model_path, clips_dir = sys.argv[1], sys.argv[2]
import pathlib
wavs = sorted(pathlib.Path(clips_dir).glob("*.wav"))
if not wavs:
    print(f"no WAVs in {clips_dir} — record a few saying the wake word (and a few not)")
    sys.exit(0)
model = Model(wakeword_models=[model_path], inference_framework="onnx")
for path in wavs:
    with wave.open(str(path), "rb") as w:
        if w.getframerate() != 16000 or w.getnchannels() != 1:
            print(f"{path.name}: SKIP (need 16 kHz mono)")
            continue
        audio = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16)
    model.reset()
    peak = 0.0
    for i in range(0, len(audio) - 1280, 1280):  # 80 ms frames
        for score in model.predict(audio[i:i + 1280]).values():
            peak = max(peak, float(score))
    print(f"{path.name}: peak score {peak:.3f}")
print("\nPick wake.threshold from the gap between positive and negative peaks.")
EOF
}

cmd_provenance() {
  # The weights are gitignored, so this file is the ONLY record of what made
  # them. Without it a model in models/wake/ is an unidentifiable binary.
  mkdir -p "$WAKE_DIR"
  local out="$WAKE_DIR/$MODEL_NAME.provenance.md"
  cat > "$out" <<EOF
# Provenance — $MODEL_NAME.onnx

Trained by \`brain/scripts/train-wake-word.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ) (UTC).

- Wake phrases: ${WAKE_PHRASES[*]}
- Languages: it, en (the rabbit is bilingual)
- openWakeWord: $OWW_REPO @ $OWW_REF (Apache-2.0)
- Sample generator: $SAMPLE_GEN_REPO @ $SAMPLE_GEN_REF (build-time only)
- Host: $(uname -srm)
- Training config: $TRAIN_DIR/$MODEL_NAME.yaml

## Corpora

Record here EXACTLY which background-noise and RIR corpora were used, and each
one's licence. Some (e.g. AudioSet) restrict redistribution — that governs
whether this .onnx may be shared, not just the training code.

- background: <fill in>
- RIR: <fill in>

## Licence of this artifact

The weights are ours (Apache-2.0 like the rest of the brain) SUBJECT TO the
corpora terms above. The training tools are external and not vendored.
EOF
  echo "provenance written to $out"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-}" in
    setup)      cmd_setup ;;
    datasets)   cmd_datasets ;;
    config)     cmd_config ;;
    train)      cmd_train ;;
    validate)   shift; cmd_validate "$@" ;;
    provenance) cmd_provenance ;;
    *) echo "usage: $0 {setup|datasets|config|train|validate|provenance}" >&2; exit 2 ;;
  esac
fi
